### ISSUE TITLE
Roadmap for Lab3

### ISSUE THREAD

**Issue by luco5826** [luco5826/group03-user-registration#2]
## Roadmap 
Here's the roadmap for Lab3:
- Tests
  - [x] #6
  - [x] #11
  - [x] #12
  - [x] #13
  - [x] #14
  - [x] #8
- Services
  - [x] EmailService for sending email messages _in progress_
  - [x] UserService for the management of the registration _in progress_ 
  - [x] [Scheduled job](https://reflectoring.io/spring-scheduler) to prune expired registration processes 
- Rest controllers
  - [x] POST `/user/register` endpoint for user registration (receiving a UserDTO and sending back an ActivationDTO)
  - [x] POST `/user/validate` endpoint for activation code (receiving a ActivationDTO and sending back an UserDTO)
 - Rate limiting
   - [x] #7

**Comment by fxbrit** [comment]
<img src="https://user-images.githubusercontent.com/34379516/164446164-e7b1ead3-2620-4f25-af5c-3f402d55ba98.png" width="400">
